name: Install Telco Devkit
description: Install Telco Devkit
inputs:
  arch:
    required: true
    path: the architecture of the devkit
  os:
    required: true
    path: the target operating system of the devkit
  version:
    required: true
    path: the version of the devkit
runs:
  using: composite
  steps:
    - run: |
        mkdir /tmp/telco-core-devkit && cd /tmp/telco-core-devkit
        wget https://github.com/telco/telco/releases/download/${{ inputs.version }}/telco-core-devkit-${{ inputs.version }}-${{ inputs.os }}-${{ inputs.arch }}.tar.xz -O - | tar --extract --xz
        sudo cp telco-core.h /usr/local/include/telco-core.h
        sudo cp libtelco-core.a /usr/local/lib/libtelco-core.a
      shell: bash
