name: linting
on: [push, pull_request]
jobs:
  staticcheck:
    strategy:
      matrix:
        arch: [x86_64]
        os: [linux]
        telco_version: ["16.0.13"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - uses: ./.github/actions/install-telco-devkit
        with:
          arch: ${{ matrix.arch }}
          os: ${{ matrix.os }}
          version: ${{ matrix.telco_version }}
      - run: go install honnef.co/go/tools/cmd/staticcheck@2022.1.3
      - run: ~/go/bin/staticcheck -checks all ./telco
